const TAX_RATE = 0.13;
const MINIMUM_RENTAL_DAYS = 5;
const MIN_CHARGE_DAYS_FOR_DAILY_RATE = 5;
const CDW_DAILY_RATE = 30;
const CDW_MINIMUM = 210;
const KM_PACKAGE_RATE = 350;
const TRAILER_HITCH_FEE = 150;
const EXTRA_KM_RATE = 0.41;
const GENERATOR_HOUR_RATE = 5;
const GENERATOR_DAILY_UNLIMITED_RATE = 60;
const CANCELLATION_DAILY_RATE = 20;
const CANCELLATION_MINIMUM = 240;
const BIKE_RACK_FEE = 50;
const WINTERIZATION_FEES = {
  class_a: 199.95,
  class_b: 149.95,
  class_c: 149.95,
  trailer: 149.95,
  classA: 199.95,
  classB: 149.95,
  classC: 149.95,
};
const PREP_FEES = {
  class_a: 199,
  class_b: 149,
  class_c: 149,
  trailer: 149,
  classA: 199,
  classB: 149,
  classC: 149,
};
const VALID_VEHICLE_TYPES = ["classA", "classB", "classC", "trailer"];
const SECURITY_DEPOSIT = 3000;
const AWNING_DEPOSIT = 1000;

module.exports = {
  TAX_RATE,
  MINIMUM_RENTAL_DAYS,
  MIN_CHARGE_DAYS_FOR_DAILY_RATE,
  CDW_DAILY_RATE,
  CDW_MINIMUM,
  KM_PACKAGE_RATE,
  TRAILER_HITCH_FEE,
  EXTRA_KM_RATE,
  GENERATOR_HOUR_RATE,
  GENERATOR_DAILY_UNLIMITED_RATE,
  CANCELLATION_DAILY_RATE,
  CANCELLATION_MINIMUM,
  BIKE_RACK_FEE,
  WINTERIZATION_FEES,
  PREP_FEES,
  VALID_VEHICLE_TYPES,
  SECURITY_DEPOSIT,
  AWNING_DEPOSIT,
};